### ISSUE TITLE
UTF8 Issues

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/civic-issue-finder#15]
#### Description

Some UTF-8 characters aren't getting displayed, while some are.

![screen shot 2014-09-17 at 10 57 15 am](https://cloud.githubusercontent.com/assets/595778/4308592/385e5f60-3e94-11e4-8a3b-2782c9427528.png)
Should say [Możliwość przesuwania obszaru](https://github.com/kodujdlapolski/Kulturalna-maloPolska/issues/3)

Other international characters show up just fine such as
![screen shot 2014-09-17 at 10 57 21 am](https://cloud.githubusercontent.com/assets/595778/4308606/690d7ce0-3e94-11e4-9868-a852aaf4d33d.png)

The problem probably is with our font? 
#### To Reproduce

Go to http://www.codeforamerica.org/geeks/civicissues/widget?organization_name=Code-for-Poland
#### Files

templates/*
#### Tasks
- [ ] Remove the webtype font from all the templates
- [ ] Find a nice replacement font
- [ ] Make an issue on the Code for America [website repo](https://github.com/codeforamerica/codeforamerica.org/tree/pattern-portfolio) about the font sucking.

**Comment by dan-nl** [comment]
another approach might be to place a lang="" attribute on elements which are not in english and then set the font-family as needed in the stylesheet; e.g. <style>:lang(pl) {font-family: serif;}</style> <h3 class="billboard-label" lang="pl">Możliwość przesuwania obszaru</h3>
