### ISSUE TITLE
Add search to the Civic Issue FInder

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/civic-issue-finder#30]
#### Description
One of the most requested features is to search for specific types of Issues. This is already possible somewhat through labels and organization attributes, but it leaves out programming language, project status, etc.

We just added [search to the CfAPI](http://codeforamerica.org/api/#api-projects). Examples are:
http://codeforamerica.org/api/projects?q=Bicycle
http://codeforamerica.org/api/organizations/Code-for-San-Francisco/projects?q=elections

This means we can now add search to the Civic Issue Finder.

To start we'd pass through the search parameter `q=bicycles` to the call to the CfAPI. Later we'd consider adding in the contents of issues and labels to the values being searched.

One question is should we change the embedded issues to include a search box? They'd all become interactive then. Might be simpler to just have the search term hardcoded in each embed through the embed form.
#### Files
app.py, templates/index.html, templates/widget.html, templates/embed.html, static/main.js

#### Tasks
- [ ] Write tests for how we expect search to work
- [ ] Pass the search parameter through on the call to the CfAPI
- [ ] Change the embed ui to have a search field
- [ ] Change the main page to inlcude a search field
- [ ] Test out including the search field on every embed?

**Comment by ondrae** [comment]
@tmaybe Having search included in each embed will probably lead to the most use of your recent work on the CfAPI.

**Comment by werdnanoslen** [comment]
I just noticed this once had ```ready``` tag on it. What's the status on this?
