### ISSUE TITLE
Add project specific Issue Finder view

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/civic-issue-finder#31]
#### Description
We got a low priority request from @spjika to show the issues from specific projects. We can't do this yet and should add the ability. A few different hurdles in setting this up.
* The CfAPI is ephemeral, meaning the project ids aren't guaranteed to not change in the future. We would want a Brigade to hardcode in a link like http://codeforamerica.org/api/projects/4664 in their website. Instead using the GitHub url would work. The closest you can get is using search like http://codeforamerica.org/api/organizations/Code-for-San-Francisco/projects?q=https://github.com/sfbrigade/sfbrigade.github.io
* The Issue Finder expects `issues` to be the top level response. Right now, specific projects don't have an /issues endpoint, so the Issue Finder code would need to know to navigate down to the issues.

I called this low priority, because people can easily roll their own version of this feature using either the CfAPI or GitHub's API.

#### Files
app.py, templates/embed.html

#### Tasks
- [ ] On the [embed form](http://www.codeforamerica.org/geeks/civicissues/embed) if a specific group is chosen, then show another drop down which lists all of that groups projects.
- [ ] If a specific project is chose, then have the widget url be something like `https://www.codeforamerica.org/geeks/civicissues/widget?organization_name=Code-for-San-Francisco&project=https://github.com/sfbrigade/sfbrigade.github.io`
- [ ] Have that url ask the CfAPI for `http://codeforamerica.org/api/organizations/Code-for-San-Francisco/projects?q=https://github.com/sfbrigade/sfbrigade.github.io`
- [ ] The Issue Finder will need to know to look for `response['objects']['issues']` rather than just `response['objects']`
